apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-banskabystrica-ovzdusie
  namespace: banskabystrica
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Air quality in Banská Bystrica
    sk: Ovzdušie v Banskej Bystrici
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: banskabystrica-verejne
  enabledRepresentations:
  - ngsi-ld
  - geojson
  slug: 32ea6ze7db7g6u7qnlgezpwp75
