apiVersion: joinedcontext.com/v1alpha1
kind: Group
metadata:
  name: air-quality-viewer
  namespace: org
  annotations:
    joinedcontext.com/app: helsinki/air-quality
spec:
  description: The viewers of air-quality, its default group (AP-118).
  members:
  - user: demo.viewer@hel.fi
