apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-air-weather-explorer
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Air quality and weather
    fi: Ilmanlaatu ja sää
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  slug: pdqvdmqvit32on6sswimb7w7a5
