apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-helsinki-events
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Helsinki events
    fi: Helsingin tapahtumat
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  - geojson
  slug: 4c46xgliyrxuvhjcxwzcglyvdm
