apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-helsinki-alerts
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Helsinki traffic alerts
    fi: Helsingin liikennetiedotteet
spec:
  allowedProjects:
  - helsinki
  audience: project-list
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  - geojson
  roles:
  - name: viewer
    subjects:
    - group: helsinki-alerts-viewer
  - name: steward
    subjects:
    - group: helsinki-alerts-steward
  slug: i6iifp45hfz5ukwtnkn3pgdchg
