apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-banskabystrica-data
  namespace: banskabystrica
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Data of Banská Bystrica
    sk: Dáta mesta Banská Bystrica
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: banskabystrica-verejne
  enabledRepresentations:
  - ngsi-ld
  - geojson
  - csv
  slug: fq4xw2ztnbe7rcav3ms6kd5ypu
