apiVersion: joinedcontext.com/v1alpha1
kind: Policy
metadata:
  name: app-banskabystrica-ovzdusie-1
  namespace: banskabystrica
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
spec:
  assignee:
    id: endpoint:banskabystrica/app-banskabystrica-ovzdusie
    kind: role
  assigner: did:web:hel.fi
  contextSpaceRef:
    kind: ContextSpace
    name: banskabystrica-verejne
  information:
  - entities:
    - type: AirQualityObserved
    propertyNames:
    - name
    - dateObserved
    - location
    - pm10
    - pm25
    - dataProvider
    relationshipNames:
    - name
    - dateObserved
    - location
    - pm10
    - pm25
    - dataProvider
  operations:
  - queryEntity
  - retrieveEntity
