apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-zilina-vyskum
  namespace: zilina
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Open research of the University of Žilina
    sk: Otvorený výskum Žilinskej univerzity
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: zilina-uniza
  enabledRepresentations:
  - ngsi-ld
  slug: u2xp2bnmai7hyioora2qdvtphr
