apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-hsl-transport
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Buses live
    fi: Bussit livenä
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  - geojson
  fileLimits:
    maxFileRows: 5000
  slug: sv4ibpmhwowb6gnzqy6vp2b3iy
