/**
 * T-3265 (EP-99): every public Endpoint dev's catalogue names has documentation a visitor reads
 * at `/d/{slug}` without signing in: its title, the entities read with an example call, and at
 * least one type with its attributes, all generated by the gateway.
 */
import { expect, test } from "@playwright/test";

test.setTimeout(600_000);

interface Detail {
  endpoint?: { url?: string };
}

test("a visitor reads the generated documentation of every public Endpoint", async ({ browser }) => {
  const context = await browser.newContext();
  const page = await context.newPage();
  try {
    const listed = (await (await page.request.get("/api/v1/catalogue")).json()) as { datasets: { name: string }[] };
    const slugs = new Set<string>();
    for (const dataset of listed.datasets) {
      const detail = (await (await page.request.get(`/api/v1/catalogue/datasets/${dataset.name}`)).json()) as Detail;
      const slug = /\/api\/endpoint\/([^/]+)\//.exec(detail.endpoint?.url ?? "")?.[1];
      if (slug) slugs.add(slug);
    }
    expect(slugs.size, "dev publishes public Endpoints").toBeGreaterThan(0);
    for (const slug of slugs) {
      const answer = await page.request.get(`/api/endpoint/${slug}/openapi.json`);
      expect(answer.status(), slug).toBe(200);
      expect(((await answer.json()) as { openapi?: string }).openapi).toBe("3.1.0");
      await page.goto(`/d/${slug}?lang=en`, { waitUntil: "load" });
      await expect(page.getByTestId("endpoint-docs")).toBeVisible({ timeout: 60_000 });
      await expect(page.getByRole("region", { name: "GET /ngsi-ld/v1/entities" })).toContainText("curl");
    }
  } finally {
    await context.close();
  }
});
