apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-news-topics
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Helsinki news topics
    fi: Helsingin uutisaiheet
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  slug: bi5og7mng4qabgu5bum336fggp
