apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-praha-mapa
  namespace: praha
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    cs: Mapa Prahy
    en: Map of Prague
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: praha-mesto
  enabledRepresentations:
  - ngsi-ld
  slug: qb3wx7nc5ztk2pmyr6hjd4vae2
