apiVersion: joinedcontext.com/v1alpha1
kind: Policy
metadata:
  name: app-air-quality-3-steward
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
spec:
  assignee:
    id: endpoint:helsinki/app-air-quality/steward
    kind: role
  assigner: did:web:hel.fi
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  information:
  - entities:
    - type: AirQualityObserved
  operations:
  - deleteEntity
  q: '!source'
