apiVersion: joinedcontext.com/v1alpha1
kind: Group
metadata:
  name: praha-odpad-viewer
  namespace: org
  annotations:
    joinedcontext.com/app: praha/praha-odpad
spec:
  description: The viewers of praha-odpad, its default group (AP-118).
  members:
  - user: demo.viewer@hel.fi
  - user: demo.steward@hel.fi
