apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-zilina-mapa
  namespace: zilina
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Map of Žilina
    sk: Mapa mesta Žilina
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: zilina-verejne
  enabledRepresentations:
  - ngsi-ld
  slug: nepjcubhzaptj2qsytzkfk5htu
