apiVersion: joinedcontext.com/v1alpha1
kind: Policy
metadata:
  name: app-bbsk-data-1
  namespace: bbsk
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
spec:
  assignee:
    id: endpoint:bbsk/app-bbsk-data
    kind: role
  assigner: did:web:hel.fi
  contextSpaceRef:
    kind: ContextSpace
    name: bbsk-registre
  information:
  - entities:
    - type: Hospital
    - type: SocialService
    - type: Bridge
    - type: PublicOrganization
    - type: AdministrativeArea
    propertyNames:
    - name
    - hospitalKind
    - operatorName
    - medicalSpecialties
    - address
    - legalId
    - serviceKind
    - serviceForm
    - targetGroup
    - capacity
    - providerKind
    - districtName
    - url
    - bridgeCode
    - roadClass
    - roadNumber
    - yearBuilt
    - spanCount
    - bridgedLength
    - structureMaterial
    - heritageStatus
    - managerName
    - alternateName
    - organizationCategory
    - areaCode
    - divisionLevel
    - surfaceArea
    relationshipNames:
    - name
    - hospitalKind
    - operatorName
    - medicalSpecialties
    - address
    - legalId
    - serviceKind
    - serviceForm
    - targetGroup
    - capacity
    - providerKind
    - districtName
    - url
    - bridgeCode
    - roadClass
    - roadNumber
    - yearBuilt
    - spanCount
    - bridgedLength
    - structureMaterial
    - heritageStatus
    - managerName
    - alternateName
    - organizationCategory
    - areaCode
    - divisionLevel
    - surfaceArea
  operations:
  - queryEntity
  - retrieveEntity
