apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-banskabystrica-mapa
  namespace: banskabystrica
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Map of Banská Bystrica
    sk: Mapa mesta Banská Bystrica
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: banskabystrica-verejne
  enabledRepresentations:
  - ngsi-ld
  slug: kz3c7bq2mxa6wdr4tnyh5pje7f
