apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-kpi-forecast
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: 'Helsinki KPIs: trend and forecast'
    fi: 'Helsingin mittarit: trendi ja ennuste'
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki-kpi
  enabledRepresentations:
  - ngsi-ld
  slug: dljgcex3vmybwkwrguionszkcv
