apiVersion: joinedcontext.com/v1alpha1
kind: Policy
metadata:
  name: app-bike-stations-1
  namespace: helsinki-mobility
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
spec:
  assignee:
    id: endpoint:helsinki-mobility/app-bike-stations
    kind: role
  assigner: did:web:hel.fi
  contextSpaceRef:
    kind: ContextSpace
    name: mobility
  information:
  - entities:
    - type: BikeHireDockingStation
    propertyNames:
    - name
    - location
    - availableBikeNumber
    - freeSlotNumber
    - totalSlotNumber
    - status
    - dateModified
    relationshipNames:
    - name
    - location
    - availableBikeNumber
    - freeSlotNumber
    - totalSlotNumber
    - status
    - dateModified
  operations:
  - queryEntity
  - retrieveEntity
