apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-helsinki-bikes
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Helsinki city bikes
    fi: Helsingin kaupunkipyörät
spec:
  audience: organization
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  - geojson
  slug: jbbdk2657lsp3mp7bt76ukc4ac
