apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-alerts-desk
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Alerts desk
    fi: Tiedotepöytä
spec:
  allowedProjects:
  - helsinki
  audience: project-list
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  slug: ed22hwvdlgbhrpawv72rgfoyi4
