apiVersion: joinedcontext.com/v1alpha1
kind: Policy
metadata:
  name: app-zilina-ukazovatele-1
  namespace: zilina
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
spec:
  assignee:
    id: endpoint:zilina/app-zilina-ukazovatele
    kind: role
  assigner: did:web:hel.fi
  contextSpaceRef:
    kind: ContextSpace
    name: zilina-kpi
  information:
  - entities:
    - type: KeyPerformanceIndicator
    propertyNames:
    - name
    - currentValue
    - calculationPeriod
    - calculationFormula
    - updatedAt
    relationshipNames:
    - name
    - currentValue
    - calculationPeriod
    - calculationFormula
    - updatedAt
  operations:
  - queryEntity
  - retrieveEntity
