apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-district-compare
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Compare districts
    fi: Vertaa kaupunginosia
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  slug: 2yawubrec4dv22ty3pyksixi7r
