apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-air-quality
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Air quality
    fi: Ilmanlaatu
spec:
  allowedProjects:
  - helsinki
  audience: project-list
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  - geojson
  fileLimits:
    maxFileRows: 5000
  roles:
  - name: viewer
    subjects:
    - group: air-quality-viewer
  - name: steward
    subjects:
    - group: air-quality-steward
  slug: 3jlwl5dg2oidblwqhc6qdi3zxl
