apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-zilina-zaznamy
  namespace: zilina
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Open data about Žilina
    sk: Otvorené dáta o Žiline
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: zilina-verejne
  enabledRepresentations:
  - ngsi-ld
  slug: ecifgir4dzgl7h45rwvty2ygyb
