import type { Lang } from "./i18n";

/** The page's words, Finnish and English. */
const TEXTS = {
  title: { fi: "Ilmanlaatu ja sää", en: "Air quality and weather" },
  page: { fi: "Vertailu", en: "Compare" },
  language: { fi: "Kieli", en: "Language" },
  station: { fi: "Ilmanlaatuasema", en: "Air quality station" },
  weatherStation: { fi: "Sääasema", en: "Weather station" },
  nearest: { fi: "{name} ({km} km)", en: "{name} ({km} km)" },
  period: { fi: "Ajanjakso", en: "Period" },
  days: { fi: "{n} vrk", en: "{n} days" },
  day1: { fi: "1 vrk", en: "1 day" },
  window: { fi: "Liukuva keskiarvo", en: "Rolling mean" },
  hours: { fi: "{n} h", en: "{n} h" },
  pollutant: { fi: "Saaste", en: "Pollutant" },
  variable: { fi: "Säämuuttuja", en: "Weather variable" },
  answer: { fi: "Vastaus", en: "The answer" },
  rises: { fi: "{air} nousee, kun {weather} nousee", en: "{air} rises as {weather} rises" },
  falls: { fi: "{air} laskee, kun {weather} nousee", en: "{air} falls as {weather} rises" },
  none: { fi: "{air} ei juuri seuraa muuttujaa {weather}", en: "{air} hardly moves with {weather}" },
  strong: { fi: "voimakkaasti", en: "strongly" },
  moderate: { fi: "kohtalaisesti", en: "moderately" },
  weak: { fi: "heikosti", en: "weakly" },
  evidence: { fi: "Spearman {rho}, Pearson {r}, {n} yhteistä tuntia.", en: "Spearman {rho}, Pearson {r}, over {n} common hours." },
  notEnough: { fi: "Yhteisiä tunteja on liian vähän sanomaan mitään. Valitse pidempi jakso tai toinen asema.", en: "Too few common hours to say anything. Pick a longer period or another station." },
  matrix: { fi: "Korrelaatiot (Spearman)", en: "Correlations (Spearman)" },
  table: { fi: "Kaikki parit", en: "Every pair" },
  pair: { fi: "Pari", en: "Pair" },
  series: { fi: "{air} ja {weather} tunneittain", en: "{air} and {weather} by the hour" },
  outlier: { fi: "Poikkeava lukema", en: "Outlying reading" },
  outliers: { fi: "{n} poikkeavaa lukemaa ({air})", en: "{n} outlying readings ({air})" },
  map: { fi: "Asemat", en: "Stations" },
  mapLabel: { fi: "Ilmanlaatu- ja sääasemat; valittu korostettuna", en: "Air quality and weather stations, the chosen ones highlighted" },
  airKind: { fi: "ilmanlaatu", en: "air quality" },
  weatherKind: { fi: "sää", en: "weather" },
  chosen: { fi: "valittu", en: "chosen" },
  reading: { fi: "Luetaan mittauksia…", en: "Reading the measurements…" },
  computing: { fi: "Lasketaan…", en: "Computing…" },
  noStations: { fi: "Ilmanlaatuasemia ei löytynyt.", en: "No air quality station was found." },
  noHistory: { fi: "Valitulta jaksolta ei ole mittauksia.", en: "No measurements in the chosen period." },
  unreadable: { fi: "Mittauksia ei voitu lukea (HTTP {status}). Yritä myöhemmin uudelleen.", en: "The measurements could not be read (HTTP {status}). Try again later." },
  offline: { fi: "Mittauksia ei voitu lukea. Tarkista yhteys ja yritä uudelleen.", en: "The measurements could not be read. Check the connection and try again." },
  failed: { fi: "Vertailua ei voitu laskea: {why}", en: "The comparison could not be computed: {why}" },
  retry: { fi: "Yritä uudelleen", en: "Retry" },
  keep: { fi: "Tallenna tai vie vertailu", en: "Keep or export the comparison" },
  compareName: { fi: "Vertailun nimi (valinnainen)", en: "Name of the comparison (optional)" },
  compareNameHint: { fi: "esim. Kallio ja tuuli", en: "e.g. Kallio and the wind" },
  save: { fi: "Tallenna vertailu", en: "Save the comparison" },
  saving: { fi: "Tallennetaan…", en: "Saving…" },
  saved: { fi: "Vertailu tallennettu. Kuka tahansa linkin saanut voi avata sen.", en: "Comparison saved. Anyone with the link can open it." },
  export: { fi: "Vie tunnit (CSV)", en: "Export the hours (CSV)" },
  exportBusy: { fi: "Viedään…", en: "Exporting…" },
  exporting: { fi: "CSV-tiedosto ladataan.", en: "The CSV file is downloading." },
  compareLink: { fi: "Linkki vertailuun", en: "Link to the comparison" },
  copy: { fi: "Kopioi linkki", en: "Copy link" },
  copied: { fi: "Linkki kopioitu.", en: "Link copied." },
  copyByHand: { fi: "Linkki on valittu: kopioi se näppäimistöllä.", en: "The link is selected: copy it with the keyboard." },
  opening: { fi: "Avataan tallennettua vertailua…", en: "Opening the saved comparison…" },
  opened: { fi: "Tallennettu vertailu avattu: {name}.", en: "Saved comparison opened: {name}." },
  openedUnnamed: { fi: "Tallennettu vertailu avattu.", en: "Saved comparison opened." },
  saveFailed: { fi: "Ei tallennettu", en: "Not saved" },
  exportFailed: { fi: "Ei viety", en: "Not exported" },
  openFailed: { fi: "Vertailua ei avattu", en: "The comparison did not open" },
  compareGone: { fi: "Tällä linkillä ei ole tallennettua vertailua.", en: "No comparison is saved under this link." },
  serverOffline: { fi: "Palvelimeen ei saatu yhteyttä. Tarkista yhteys ja yritä uudelleen.", en: "The server could not be reached. Check the connection and try again." },
  serverDown: { fi: "Palvelin ei vastannut. Yritä hetken päästä uudelleen.", en: "The server did not answer. Try again in a moment." },
  signInAgain: { fi: "Kirjaudu uudelleen sisään ja yritä uudelleen.", en: "Sign in again, then try again." },
  noRight: { fi: "Mittauksia ei saa lukea tällä tunnuksella.", en: "This account may not read the measurements." },
  storageFull: { fi: "Sovelluksen tallennustila on täynnä. Yritä huomenna uudelleen.", en: "The app's storage is full. Try again tomorrow." },
  open: { fi: "Tiedot: {name}", en: "Details of {name}" },
  pm10: { fi: "PM10 (µg/m³)", en: "PM10 (µg/m³)" },
  pm25: { fi: "PM2.5 (µg/m³)", en: "PM2.5 (µg/m³)" },
  airQualityIndex: { fi: "ilmanlaatuindeksi", en: "air quality index" },
  temperature: { fi: "lämpötila (°C)", en: "temperature (°C)" },
  windSpeed: { fi: "tuulen nopeus (m/s)", en: "wind speed (m/s)" },
  relativeHumidity: { fi: "ilmankosteus (%)", en: "humidity (%)" },
  precipitation: { fi: "sade (mm/h)", en: "rain (mm/h)" },
} as const;

export type Key = keyof typeof TEXTS;

/** The text of `key` in `lang`, each `{name}` replaced by `values[name]`. */
export function t(lang: Lang, key: Key, values: Record<string, string | number> = {}): string {
  return TEXTS[key][lang].replace(/\{(\w+)\}/g, (whole, name: string) => (name in values ? String(values[name]) : whole));
}
