apiVersion: joinedcontext.com/v1alpha1
kind: Endpoint
metadata:
  name: app-data-quality-inspector
  namespace: helsinki
  annotations:
    joinedcontext.com/generated-by: portal/app-reconciler
  title:
    en: Helsinki data quality
    fi: Helsingin datan laatu
spec:
  audience: public
  callerRole: true
  contextSpaceRef:
    kind: ContextSpace
    name: helsinki
  enabledRepresentations:
  - ngsi-ld
  slug: rywjgug3g32ayfjwkzr5j3tqom
